### ISSUE TITLE
ES6 not transpiled in npm package

### ISSUE THREAD

**Issue by alemhnan** [gausie/loopback-softdelete-mixin#1]
Hi,

I am testing the package and it works correctly. Although to actually use the package I need to run npm install inside the package itself because I get a 'Error: Cannot find module 'babel-runtime/core-js/promise''. 

The original package from which softdelete is inspired (ds-timestamp) has also the transpiled files committed (here they are gitignored) , could be possible to have the same situation here?

**Comment by gausie** [comment]
I'll sort this out now!

**Comment by gausie** [comment]
Fixed in 7770fc3 (v0.0.5)

**Comment by alemhnan** [comment]
In 7770fc3 I see just the version changed in package.json but no other files touched?

**Comment by gausie** [comment]
Correct, I pushed the files to npm and need to update the package number for it to accept new files. They're in gitignore though, so no apparent change on here.

**Comment by alemhnan** [comment]
I am still getting the same error, soft-delete.js requires babel-runtime/core-js/promise that is not included in the dependencies (there are of course babel-\* packages but in the devDeps so they are not installed).

**Comment by gausie** [comment]
Quite right, I misunderstood the babel-runtime plugin. Reopening for a bit.

**Comment by gausie** [comment]
Ok that should sort that out.
